---
title: "Analysis of Mars et al., 2020 data"
output: html_document
date: "2025-05-09"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download data

```
parallel --jobs 10 --halt soon,fail=1 --joblog parallel_joblog.txt < download.sh 2> parallel_errors.log
```


## Run Sylph

```
sylph query gtdb_ordered_99.syldb -u --read-seq-id 99.9 -t 100  -1 ./*_1.fastq.gz -2 ./*_2.fastq.gz -o ./mars_2020_query_gtdb_220_id99.tsv ./ERR*[0-9][0-9].fastq.gz
sylph profile /data1/gerryt/sylph_analyses/gtdb_98_ordered_DB/gtdb_ordered_98.syldb -u --read-seq-id 99.9 -t 100  -1 ./*_1.fastq.gz -2 ./*_2.fastq.gz -o ./mars_2020_profile_gtdb_220_id98.tsv ./ERR*[0-9][0-9].fastq.gz
sylph profile /data1/gerryt/sylph_analyses/gtdb-r220-c200-dbv1.syldb -u --read-seq-id 99.9 -t 100  -1 ./*_1.fastq.gz -2 ./*_2.fastq.gz -o ./mars_2020_profile_gtdb_220_id95.tsv ./ERR*[0-9][0-9].fastq.gz
```

#Initial plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

