---
title: "Sims_microbial_load"
output:
  github_document
date: "2025-05-16"
editor_options:
  chunk_output_type: console
---

# Analysing the dataset from Mars et al. 2020 
## Loading and preprocessing data
```{r, warning=FALSE}
library(strainspy)
library(ggplot2)
library(dplyr)
library(tidyr)

se_98_abundance <- readRDS("TEST_DATA/mars_2020/Filtered/mars_2020_profile_gtdb_220_id98_abundance.rds")
se_metaphlan <- readRDS("TEST_DATA/mars_2020/Filtered/mars_2020_metaphlan_profile.rds")
se_98_ANI <- readRDS("TEST_DATA/mars_2020/Filtered/mars_2020_profile_gtdb_220_id98_ANI.rds")
load_galaxy = readRDS("TEST_DATA/mars_2020/Filtered/microbial_load_galaxy.rds")
load_metacardis = readRDS("TEST_DATA/mars_2020/Filtered/microbial_load_metacardis.rds")
metadata = readRDS("TEST_DATA/mars_2020/Filtered/metadata.rds")

## add load data
if(all(names(load_galaxy) == metadata$Accession) ) metadata$load_g = load_galaxy else cat("Names not in order")
if(all(names(load_metacardis) == metadata$Accession) ) metadata$load_m = load_metacardis else cat("Names not in order")

se_metaphlan = strainspy:::modify_metadata(se = se_metaphlan, meta_data = metadata)
se_98_abundance = strainspy:::modify_metadata(se = se_98_abundance, meta_data = metadata)
se_98_ANI = strainspy:::modify_metadata(se = se_98_ANI, meta_data = metadata)

# filter out mostly zero entries (~5%)
se_98_ANI <- filter_by_presence(se_98_ANI, min_nonzero = 25)
se_98_abundance <- filter_by_presence(se_98_abundance, min_nonzero = 25)
se_metaphlan <- filter_by_presence(se_metaphlan, min_nonzero = 25)
```
## Visualising Distributions
H = Healthy, C = IBS-C, D = IBS-D
```{r, warning=FALSE}
ggplot(metadata, aes(x = cohort, fill = cohort)) +
  geom_bar() +
  labs(title = "Sample Count per Cohort", x = "Cohort", y = "Count") +
  theme_minimal()

ggplot(metadata, aes(x = gender, y = age, fill = gender)) +
  geom_violin(trim = FALSE) +
  geom_jitter(width = 0.2, alpha = 0.3) +
  labs(title = "Age Distribution by Gender", x = "Gender", y = "Age") +
  theme_minimal()

ggplot(metadata, aes(x = cohort, y = BMI, fill = cohort)) +
  geom_boxplot() +
  labs(title = "BMI by Cohort", x = "Cohort", y = "BMI") +
  theme_minimal()

ggplot(metadata, aes(x = load_g, y = load_m, color = cohort)) +
  geom_point(alpha = 0.6) +
  labs(title = "Microbial Load by Cohort", x = "Galaxy model", y = "Metacardis model") +
  theme_minimal()

ggplot(metadata, aes(x = timepoint, y = patientID, color = as.factor(flare))) +
    geom_point(size = 3) +
    facet_wrap(~ cohort, scales = "free_y") +
    scale_color_manual(values = c("0" = "grey70", "1" = "red"), name = "Flare") +
    labs(title = "Sample availability", x = "Timepoint", y = "Patient ID") +
    theme_minimal()

binary_vars <- c("antibiotics", "probiotics", "pain_meds", "yogurt")
meta_long <- metadata %>%
  select(patientID, cohort, all_of(binary_vars)) %>%
  distinct() %>%
  pivot_longer(cols = binary_vars, names_to = "variable", values_to = "value") %>%
  group_by(cohort, variable) %>%
  summarise(proportion = mean(value), .groups = "drop")

ggplot(meta_long, aes(x = cohort, y = proportion, fill = cohort)) +
  geom_col(position = "dodge") +
  facet_wrap(~variable, scales = "free_y") +
  labs(y = "Proportion", x = "Cohort", title = "Covariate Distribution") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")

```
## Modelling ANI
### Ordinal Beta
```{r, warning=FALSE}
design <- as.formula("~ cohort + timepoint + age + BMI + gender + antibiotics + probiotics + yogurt + pain_meds + (1 + timepoint | patientID)")

fit_ANI = glmZiBFit(se_98_ANI, design, nthreads = parallel::detectCores())
top_hits(fit_ANI, coef = 2) # IBS-C compared to Healthy
plot_manhattan(fit_ANI, coef = 2)

top_hits(fit_ANI, coef = 3) # IBS-D compared to Healthy
plot_manhattan(fit_ANI, coef = 3)
# There are some 0 p-values, looking in to this soon...

contigs = unique(c(top_hits(fit_ANI, 2)$Contig_name, top_hits(fit_ANI,3)$Contig_name)); 
plot_ani_dist(se_98_ANI, 'cohort', contigs)
  
```
### ZIB
```{r, warning=FALSE}
design <- as.formula("~ cohort + timepoint + age + BMI + gender + antibiotics + probiotics + yogurt + pain_meds + (1 + timepoint | patientID)")
fit_ANI_zb = glmZiBFit(se_98_ANI, design, 10L)
top_hits(fit_ANI_zb, coef = 2)
top_hits(fit_ANI_zb, coef = 3)
plot_manhattan(fit_ANI_zb, coef = 2)
plot_manhattan(fit_ANI_zb, coef = 3)
contigs = unique(c(top_hits(fit_ANI_zb, 2)$Contig_name, top_hits(fit_ANI_zb,3)$Contig_name)) 
if(length(contigs) > 0) {
  plot_violin(se_98_ANI, 'cohort', contigs, drop_zeros = T, contig_names = NULL)
  plot_volcano(fit_ANI, label = T)
}
```
## Modelling Abundance
```{r, warning=FALSE}
design <- as.formula("~ cohort + (1 | patientID)")

fit_AB_skani = abundanceFit(se = se_98_abundance, design = design, nthreads = 10L, transform = 'CLR')
top_hits(fit_AB_skani, coef = 2)
top_hits(fit_AB_skani, coef = 3)
plot_manhattan(fit_AB_skani)
contigs = unique(c(top_hits(fit_AB_skani, 2)$Contig_name, top_hits(fit_AB_skani,3)$Contig_name))
if(length(contigs) > 0) {
  plot_violin(se_98_abundance, 'cohort', contigs, drop_zeros = T, contig_names = NULL)
  plot_volcano(fit_AB_skani, label = T)
}

fit_AB_metaphlan = abundanceFit(se = se_metaphlan, design = design, nthreads = 10L, transform = 'CLR')
top_hits(fit_AB_metaphlan, coef = 2)
top_hits(fit_AB_metaphlan, coef = 3)
plot_manhattan(fit_AB_metaphlan)
contigs = unique(c(top_hits(fit_AB_metaphlan, 2)$Contig_name, top_hits(fit_AB_metaphlan,3)$Contig_name)) 
if(length(contigs) > 0) {
  plot_violin(se_98_abundance, 'cohort', contigs, drop_zeros = T, contig_names = NULL)
  plot_volcano(fit_AB_metaphlan, label = T)
}
```
